---
- name: For packer app
  hosts: app # hosts
  vars:
    mongo_bind_ip: 0.0.0.0 # Set variable
    jsondata: "{{ lookup('file', './static_inventory.json') | from_json}}"


##### Tasks:
  tasks:
    # - name: Get_vars_from_static_inv_output.json
    #   include_vars:
    #     file: ./static_inventory.json
    - name: Set db_host
      ansible.builtin.set_fact:
        db_host: "{{ hostvars[inventory_hostname].internal_ip }}"

# - name: Set_vars_from_file
#   ansible.builtin.set_fact:
#     web_ip: "{{ hostvars[hosts['app'].hosts[0]] }}"
#     db_ip: "{{ hostvars[hosts['db'].hosts[0]] }}"
#     # web_ip: "{{ hostvars[groups['app'][0]].ansible_host }}"
#     # db_ip: "{{ hostvars[groups['db'][0]].ansible_host }}"


###### initial tasks
    - name: Set app server name variables
      ansible.builtin.set_fact:
        web_name: "{{ item.key }}"
      with_dict: "{{ jsondata.all.hosts }}"
      when: "'app' in item.key"
      delegate_to: 127.0.0.1

    - name: Set web_ip variables
      ansible.builtin.set_fact:
        web_ip: "{{ item.value.ansible_host }}"
      with_dict: "{{ jsondata.all.hosts }}"
      when: "'app' in item.key"
      no_log: true
      delegate_to: 127.0.0.1


# also work
# web_ip: "{{ (jsondata.all.hosts | dict2items | selectattr('key', 'match', '.*app.*') | list | first).value.ansible_host }}"
# db_ip: "{{ (jsondata.all.hosts | dict2items | selectattr('key', 'match', '.*db.*') | list | first).value.ansible_host }}"

###### Debug task
    # - name: Print web_ip and db_ip
    #   ansible.builtin.debug:
    #     var: web_name,db_name,db_host


    - name: Add_unitd_file_for_Puma
      become: true
      ansible.builtin.copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: "0644"
      when: inventory_hostname == web_name

      notify: Reload_puma_service

    - name: Add_config_DB_connection
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      when: inventory_hostname == web_name

    - name: Enabled_puma
      become: true
      ansible.builtin.systemd:
        name: puma
        enabled: true
        daemon_reload: true
      when: inventory_hostname == web_name

    - name: Install ruby, and needed dep's
      become: true
      ansible.builtin.apt:
        update-cache: true
        name: "{{ item }}"
        state: present
      loop:
        - git
        - ruby-full
        - ruby-bundler
        - build-essential
      loop_control:
        loop_var: item

    - name: Set_permission
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        recurse: true
      loop:
        - /home/ubuntu/reddit/
      when: inventory_hostname == web_name


    - name: Get_the_code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        force: true
        version: monolith # set the useful branch
      when: inventory_hostname == web_name
      notify: Reload_puma_service

    - name: Bundle_install
      community.general.bundler:
        state: present
        chdir: /home/ubuntu/reddit
      when: inventory_hostname == web_name

##### Handlers:

  handlers:
    - name: Reload_puma_service
      become: true
      ansible.builtin.service:
        name: puma
        state: restarted
...
